// A sidebar é gerada pelas pastas de /docs. Página nova criada no editor
// aparece sozinha na seção certa — ninguém precisa mexer aqui.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};
export default sidebars;
