// 4 sidebars, um por item do navbar. Cada um lê os arquivos da sua pasta.
// Novo arquivo criado no editor aparece sozinho na seção certa.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  vidaDs: [{type: 'autogenerated', dirName: 'vida-ds'}],
  nossoTime: [{type: 'autogenerated', dirName: 'nosso-time'}],
  researchOps: [{type: 'autogenerated', dirName: 'research-ops'}],
  guias: [{type: 'autogenerated', dirName: 'guias'}],
};
export default sidebars;
